[sources.generate_syslog]
  type = "demo_logs"
  format = "syslog"
  count = 10

[sinks.raw_syslog]
  inputs = ["generate_syslog"]
  type = "file"
  path = "raw_demo_syslog.log"

[sinks.raw_syslog.encoding]
  codec = "text"
